### PR TITLE
Laplacian quality using determinant

### PR DESCRIPTION
**Pull request by razimantv**
Added determinant-based laplacian quality. Currently finding determinant by turning the matrix dense. It is also possible to do it with LU decomposition, but that seems slow for the smaller matrices I tried.

TODO: Add Luigi config to select quality determination method

### CODE REVIEW

**Comment by arnaudon** [comment]
thanks, I'll add this option in luigi and merge asap

**Comment by arnaudon** [comment]
@razimantv , try this update with 
quality_method=determinant in section [ModeSearchConfig] to see if it works!

**Comment by razimantv** [comment]
Finds passive modes but only if I call  `find_rough_modes_from_scan` with a reduced `threshold_abs` of 0.01 and set `quality_threshold` in the config to 1.

**Comment by arnaudon** [comment]
ah yes, these values are wrt to quality value, which changes if you compute eig or svd, or det. So this PR works for you, I can merge?

**Comment by arnaudon** [comment]
ah sorry, I didn't realise this is not in luigi, ok I'll add it

**Comment by arnaudon** [comment]
here you are, I added also min_distance, just in case!

**Pull request merged**
