### PR TITLE
some plotting updates

### PR DESCRIPTION
**Pull request by arnaudon**
some updates in plotting following slack discussions
also, take a look at plotting.plot_mode_evolution, it makes a bunch of mode profile plots as a function of D0, it's nice to make a little video or so to see the mode profile changes.

### CODE REVIEW

**Comment by arnaudon** [comment]
@razimantv , have a try, and let me know if it's good to use as it is, then I'll merge

**Review by razimantv — APPROVED** [review]
Most plot issues seem fixed, thanks! There is still the annoying tiny mismatch between the x1 and x2 axes in the stem spectra 🤔

**Comment by razimantv** [comment]
Sorry, after I did the review I just saw the suggestion to merge and forgot about your comment above :)

**Comment by arnaudon** [comment]
no probleme, the green button is always very attractive haha

**Pull request merged**
